const fontImports = `
@import url('https://fonts.googleapis.com/css2?family=Teko:wght@500;600;700&family=Inter:wght@400;500;600;700&family=IBM+Plex+Mono:wght@500;600&display=swap');

html {
  -webkit-font-smoothing: antialiased;
  -moz-osx-font-smoothing: grayscale;
  text-rendering: optimizeLegibility;
}
body {
  margin: 0;
  background: #0E1014;
}
* {
  -webkit-tap-highlight-color: transparent;
}
::selection {
  background: rgba(61, 220, 151, 0.25);
  color: #EDEFF3;
}

/* Layout mobile-first, tapi dilebarin bertahap di layar lebih gede biar
   nggak keliatan nyempit terus-terusan di desktop/browser */
.jo-content {
  max-width: 640px;
}
.jo-modal {
  max-width: 100%;
  width: 100%;
}
/* Tablet: medium form */
@media (min-width: 600px) {
  .jo-modal {
    max-width: 560px !important;
    border-radius: 12px !important;
    margin: 24px auto;
  }
  .jo-overlay-center {
    align-items: center !important;
    padding: 16px !important;
  }
}
/* Desktop: wide efficient form (up to 720px) */
@media (min-width: 900px) {
  .jo-content { max-width: 820px; }
  .jo-modal {
    max-width: 720px !important;
  }
  .jo-modal input,
  .jo-modal textarea,
  .jo-modal .jo-input {
    font-size: 13px !important;
    padding: 9px 11px !important;
    min-height: 0 !important;
  }
  .jo-modal button {
    min-height: 40px !important;
    font-size: 13px !important;
    padding: 9px 12px !important;
  }
}
@media (min-width: 1280px) {
  .jo-content { max-width: 980px; }
}
/* Stack on mobile; side-by-side name/round on wider screens */
.jo-form-row {
  display: flex;
  flex-direction: column;
  gap: 0;
}
.jo-form-row > input {
  flex: 1;
  min-width: 0;
  width: 100%;
}
@media (min-width: 700px) {
  .jo-form-row {
    flex-direction: row;
    gap: 10px;
  }
}
`;

const styles = {
  page: {
    minHeight: "100vh",
    background: "radial-gradient(ellipse 120% 80% at 50% -20%, #1A2030 0%, #0E1014 55%)",
    color: "#EDEFF3",
    fontFamily: "'Inter', system-ui, -apple-system, sans-serif",
    padding: "0 16px 80px",
    boxSizing: "border-box",
  },
  muted: { color: "#767C89", fontFamily: "'IBM Plex Mono', monospace" },
  header: {
    position: "sticky",
    top: 0,
    zIndex: 20,
    background: "rgba(14, 16, 20, 0.92)",
    margin: "0 auto",
    padding: "20px 0 16px",
    display: "flex",
    flexWrap: "wrap",
    justifyContent: "space-between",
    alignItems: "flex-start",
    gap: 10,
    borderBottom: "1px solid rgba(44, 48, 58, 0.9)",
    transition: "padding 0.2s ease, background 0.2s ease",
    width: "100%",
    boxSizing: "border-box",
    overflow: "hidden",
  },
  headerCollapsed: {
    position: "sticky",
    top: 0,
    zIndex: 20,
    background: "rgba(14, 16, 20, 0.94)",
    margin: "0 auto",
    padding: "10px 0",
    display: "flex",
    flexWrap: "wrap",
    justifyContent: "space-between",
    alignItems: "center",
    gap: 8,
    borderBottom: "1px solid #2C303A",
    transition: "padding 0.2s ease",
    width: "100%",
    boxSizing: "border-box",
    overflow: "hidden",
  },
  brandRow: {
    display: "flex",
    alignItems: "center",
    gap: 10,
    flex: "1 1 160px",
    minWidth: 0,
  },
  brandLogo: {
    width: 48,
    height: 48,
    objectFit: "cover",
    borderRadius: 12,
    border: "1px solid #2C303A",
    flexShrink: 0,
    transition: "width 0.2s ease, height 0.2s ease",
    cursor: "pointer",
  },
  brandLogoSmall: {
    width: 28,
    height: 28,
    objectFit: "cover",
    borderRadius: 8,
    border: "1px solid #2C303A",
    flexShrink: 0,
    transition: "width 0.2s ease, height 0.2s ease",
    cursor: "pointer",
  },
  headlineCompactRow: { display: "flex", alignItems: "center", gap: 6, minWidth: 0 },
  headlineCompact: {
    fontFamily: "'Teko', sans-serif",
    fontSize: 18,
    fontWeight: 600,
    letterSpacing: "0.02em",
    color: "#F5F7FA",
    whiteSpace: "nowrap",
    overflow: "hidden",
    textOverflow: "ellipsis",
    maxWidth: "100%",
  },
  devDot: {
    width: 8,
    height: 8,
    borderRadius: "50%",
    background: "#F2C14E",
    flexShrink: 0,
  },
  eyebrow: {
    fontFamily: "'IBM Plex Mono', monospace",
    fontSize: 11,
    letterSpacing: "0.18em",
    color: "#3DDC97",
    marginBottom: 2,
    fontWeight: 600,
  },
  headline: {
    fontFamily: "'Teko', sans-serif",
    fontSize: 36,
    fontWeight: 600,
    letterSpacing: "0.02em",
    lineHeight: 1.05,
    color: "#F5F7FA",
  },
  publicBadge: {
    fontFamily: "'IBM Plex Mono', monospace",
    fontSize: 10,
    color: "#F2C14E",
    letterSpacing: "0.04em",
    marginTop: 4,
  },
  headerNote: {
    fontSize: 12,
    color: "#8B919C",
    marginTop: 6,
    maxWidth: 340,
    lineHeight: 1.5,
  },
  addBtn: {
    background: "#3DDC97",
    color: "#14161A",
    border: "none",
    borderRadius: 3,
    padding: "9px 16px",
    fontSize: 13,
    fontWeight: 600,
    cursor: "pointer",
    fontFamily: "'Inter', sans-serif",
  },
  headerActions: {
    display: "flex",
    flexWrap: "wrap",
    gap: 6,
    alignItems: "center",
    justifyContent: "flex-end",
    flex: "0 1 auto",
    maxWidth: "100%",
  },
  pageTabs: {
    display: "flex",
    gap: 0,
    background: "rgba(20, 24, 32, 0.9)",
    border: "1px solid #2A2F3A",
    borderRadius: 10,
    overflow: "hidden",
    flexShrink: 0,
  },
  pageTab: {
    background: "transparent",
    border: "none",
    color: "#8B919C",
    fontSize: 12,
    fontWeight: 600,
    fontFamily: "'Inter', sans-serif",
    padding: "8px 12px",
    cursor: "pointer",
    minHeight: 36,
  },
  pageTabActive: {
    background: "rgba(61,220,151,0.16)",
    border: "none",
    color: "#3DDC97",
    fontSize: 12,
    fontWeight: 700,
    fontFamily: "'Inter', sans-serif",
    padding: "8px 12px",
    cursor: "pointer",
    minHeight: 36,
  },
  devToggleBtn: {
    background: "none",
    border: "1px solid #2C303A",
    color: "#767C89",
    borderRadius: 8,
    padding: "8px 10px",
    fontSize: 12,
    cursor: "pointer",
    fontFamily: "'Inter', sans-serif",
    minHeight: 36,
    whiteSpace: "nowrap",
  },
  lockBtn: {
    background: "none",
    border: "1px solid #2C303A",
    color: "#767C89",
    borderRadius: 8,
    padding: "8px 10px",
    fontSize: 12,
    cursor: "pointer",
    fontFamily: "'Inter', sans-serif",
    minHeight: 36,
    whiteSpace: "nowrap",
  },
  searchBtnActive: {
    background: "#3DDC97",
    color: "#14161A",
    borderColor: "#3DDC97",
  },
  searchBarWrap: {
    margin: "0 auto 12px",
    paddingTop: 4,
  },
  searchInputWrap: {
    position: "relative",
    display: "flex",
    alignItems: "center",
  },
  searchIcon: {
    position: "absolute",
    left: 12,
    color: "#767C89",
    fontSize: 15,
    pointerEvents: "none",
    lineHeight: 1,
  },
  searchInput: {
    width: "100%",
    background: "#1D2027",
    border: "1px solid #2A2E38",
    borderRadius: 8,
    padding: "10px 36px 10px 34px",
    color: "#EDEFF3",
    fontSize: 14,
    fontFamily: "'Inter', sans-serif",
    outline: "none",
  },
  searchClearBtn: {
    position: "absolute",
    right: 8,
    background: "transparent",
    border: "none",
    color: "#767C89",
    fontSize: 18,
    cursor: "pointer",
    padding: "4px 8px",
    lineHeight: 1,
  },
  searchResultHint: {
    marginTop: 6,
    fontSize: 12,
    color: "#767C89",
    fontFamily: "'Inter', sans-serif",
  },
  emptyState: {
    margin: "0 auto",
    color: "#8B919C",
    fontSize: 15,
    padding: "56px 12px",
    textAlign: "center",
    lineHeight: 1.5,
  },
  dateBlock: { margin: "0 auto 22px" },
  dateLabel: {
    position: "sticky",
    top: 136,
    zIndex: 10,
    background: "#14161A",
    fontFamily: "'IBM Plex Mono', monospace",
    fontSize: 12,
    color: "#F2C14E",
    letterSpacing: "0.08em",
    textTransform: "uppercase",
    display: "flex",
    flexWrap: "wrap",
    alignItems: "baseline",
    gap: 6,
    padding: "10px 0 8px",
  },
  dateLabelRange: {
    color: "#8B919C",
    fontWeight: 500,
    fontSize: 10,
    letterSpacing: "0.06em",
    textTransform: "none",
  },
  eventCard: {
    background: "linear-gradient(165deg, #1C2028 0%, #171A21 100%)",
    border: "1px solid #2A2F3A",
    borderRadius: 14,
    padding: "16px 16px 14px",
    marginBottom: 12,
    boxShadow: "0 4px 20px rgba(0,0,0,0.22)",
  },
  eventHeaderRow: {
    display: "flex",
    flexWrap: "wrap",
    justifyContent: "space-between",
    alignItems: "flex-start",
    gap: 8,
    marginBottom: 10,
  },
  eventHeaderLeft: { display: "flex", alignItems: "flex-start", gap: 10, minWidth: 0, flex: "1 1 180px" },
  eventLogoImg: {
    width: 36,
    height: 36,
    objectFit: "contain",
    borderRadius: 10,
    flexShrink: 0,
    background: "#12151B",
  },
  eventLogoFallback: {
    width: 36,
    height: 36,
    borderRadius: 10,
    background: "#12151B",
    border: "1px solid #2C303A",
    alignItems: "center",
    justifyContent: "center",
    fontFamily: "'IBM Plex Mono', monospace",
    fontSize: 10,
    fontWeight: 600,
    color: "#3DDC97",
    flexShrink: 0,
  },
  uploadBtn: {
    display: "block",
    width: "100%",
    background: "#14161A",
    border: "1px dashed #3A3F49",
    borderRadius: 10,
    color: "#3DDC97",
    padding: "14px 14px",
    fontSize: 14,
    fontWeight: 500,
    cursor: "pointer",
    fontFamily: "'Inter', sans-serif",
    textAlign: "center",
    marginBottom: 10,
    boxSizing: "border-box",
  },
  hiddenFileInput: { display: "none" },
  logoPreviewRow: { display: "flex", alignItems: "center", gap: 8, marginBottom: 10, marginTop: -4 },
  logoPreviewImg: {
    width: 28,
    height: 28,
    objectFit: "contain",
    borderRadius: 3,
    background: "#14161A",
    border: "1px solid #2C303A",
  },
  logoListRow: {
    display: "flex",
    alignItems: "center",
    gap: 8,
    padding: "6px 0",
    borderBottom: "1px solid #2C303A",
  },
  logoListName: { fontSize: 13, flex: 1, textTransform: "capitalize" },
  suggestionRow: {
    padding: "10px 0",
    borderBottom: "1px solid #2C303A",
  },
  suggestionMeta: {
    fontFamily: "'IBM Plex Mono', monospace",
    fontSize: 10,
    color: "#767C89",
    marginBottom: 4,
  },
  suggestionMessage: { fontSize: 14, marginBottom: 6, whiteSpace: "pre-wrap" },
  rowRemoveBtnText: {
    background: "none",
    border: "1px solid #2C303A",
    color: "#767C89",
    borderRadius: 3,
    padding: "4px 10px",
    fontSize: 11,
    cursor: "pointer",
    fontFamily: "'Inter', sans-serif",
  },
  eventTitleCol: { display: "flex", flexDirection: "column", gap: 2, minWidth: 0 },
  liveOnRow: { display: "flex", alignItems: "center", gap: 6, flexWrap: "wrap" },
  liveOnChannelChip: {
    display: "inline-flex",
    alignItems: "center",
    background: "#F2EFE9",
    borderRadius: 4,
    padding: "2px 5px",
  },
  liveOnChannelChipText: { display: "inline-flex", alignItems: "center" },
  liveOnLogo: {
    height: 20,
    width: "auto",
    maxWidth: 100,
    objectFit: "contain",
    display: "block",
  },
  liveOnLabel: {
    fontFamily: "'IBM Plex Mono', monospace",
    fontSize: 9,
    fontWeight: 600,
    letterSpacing: "0.14em",
    color: "#8B919C",
  },
  liveOnValue: {
    fontFamily: "'IBM Plex Mono', monospace",
    fontSize: 11,
    letterSpacing: "0.04em",
    color: "#F2C14E",
    fontWeight: 600,
  },
  eventName: {
    fontFamily: "'Teko', sans-serif",
    fontSize: 24,
    fontWeight: 600,
    letterSpacing: "0.03em",
    color: "#F5F7FA",
    lineHeight: 1.1,
  },
  eventRound: {
    fontSize: 14,
    color: "#F2C14E",
    fontWeight: 600,
    marginTop: 2,
    letterSpacing: "0.01em",
  },
  eventHeaderActions: {
    display: "flex",
    flexWrap: "wrap",
    gap: 6,
    flexShrink: 0,
    alignItems: "center",
    marginLeft: "auto",
  },
  reorderBtn: {
    background: "#14161A",
    border: "1px solid #2C303A",
    color: "#EDEFF3",
    borderRadius: 8,
    width: 36,
    height: 36,
    lineHeight: 1,
    fontSize: 14,
    cursor: "pointer",
    fontFamily: "'Inter', sans-serif",
    padding: 0,
    display: "inline-flex",
    alignItems: "center",
    justifyContent: "center",
  },
  reorderBtnDisabled: {
    background: "#14161A",
    border: "1px solid #2C303A",
    color: "#3A3F49",
    borderRadius: 8,
    width: 36,
    height: 36,
    lineHeight: 1,
    fontSize: 14,
    cursor: "not-allowed",
    fontFamily: "'Inter', sans-serif",
    padding: 0,
    display: "inline-flex",
    alignItems: "center",
    justifyContent: "center",
  },
  mergedActions: {
    marginBottom: 10,
    padding: "10px 12px",
    background: "#14161A",
    border: "1px solid #2C303A",
    borderRadius: 8,
  },
  mergedNote: {
    fontSize: 11,
    color: "#767C89",
    fontStyle: "italic",
    marginBottom: 8,
    lineHeight: 1.4,
  },
  mergedActionRow: {
    display: "flex",
    flexWrap: "wrap",
    alignItems: "center",
    gap: 6,
    padding: "6px 0",
  },
  mergedActionDate: {
    fontFamily: "'IBM Plex Mono', monospace",
    fontSize: 11,
    color: "#F2C14E",
    minWidth: 52,
    flex: "0 0 auto",
  },
  editBtn: {
    background: "rgba(61,220,151,0.12)",
    border: "1px solid #3DDC97",
    color: "#3DDC97",
    fontSize: 12,
    fontWeight: 600,
    cursor: "pointer",
    fontFamily: "'Inter', sans-serif",
    borderRadius: 8,
    minWidth: 36,
    height: 36,
    padding: "0 10px",
    display: "inline-flex",
    alignItems: "center",
    justifyContent: "center",
  },
  duplicateBtn: {
    background: "rgba(242,193,78,0.12)",
    border: "1px solid #F2C14E",
    color: "#F2C14E",
    fontSize: 12,
    fontWeight: 600,
    cursor: "pointer",
    fontFamily: "'Inter', sans-serif",
    borderRadius: 8,
    minWidth: 36,
    height: 36,
    padding: "0 10px",
    display: "inline-flex",
    alignItems: "center",
    justifyContent: "center",
  },
  deleteBtn: {
    background: "rgba(118,124,137,0.12)",
    border: "1px solid #2C303A",
    color: "#A0A6B0",
    fontSize: 12,
    fontWeight: 600,
    cursor: "pointer",
    fontFamily: "'Inter', sans-serif",
    borderRadius: 8,
    minWidth: 36,
    height: 36,
    padding: "0 10px",
    display: "inline-flex",
    alignItems: "center",
    justifyContent: "center",
  },
  pinBtn: {
    background: "none",
    border: "1px solid #2C303A",
    color: "#767C89",
    borderRadius: 8,
    width: 36,
    height: 36,
    fontSize: 14,
    cursor: "pointer",
    display: "inline-flex",
    alignItems: "center",
    justifyContent: "center",
    padding: 0,
  },
  pinBtnActive: {
    background: "rgba(242,193,78,0.15)",
    border: "1px solid #F2C14E",
    color: "#F2C14E",
    borderRadius: 8,
    width: 36,
    height: 36,
    fontSize: 14,
    cursor: "pointer",
    display: "inline-flex",
    alignItems: "center",
    justifyContent: "center",
    padding: 0,
  },
  pinBadge: {
    fontSize: 16,
    lineHeight: 1,
    flexShrink: 0,
    display: "inline-flex",
    alignItems: "center",
    justifyContent: "center",
    width: 28,
    height: 28,
  },
  matchList: { display: "flex", flexDirection: "column", gap: 6 },
  courtLabel: {
    fontFamily: "'IBM Plex Mono', monospace",
    fontSize: 10,
    fontWeight: 600,
    letterSpacing: "0.12em",
    color: "#3DDC97",
    textTransform: "uppercase",
    marginTop: 12,
    marginBottom: 4,
  },
  matchRow: {
    display: "flex",
    flexWrap: "wrap",
    alignItems: "baseline",
    columnGap: 12,
    rowGap: 4,
    padding: "8px 10px",
    background: "#14161A",
    borderRadius: 3,
    border: "1px solid #2C303A",
  },
  matchTopRow: {
    display: "flex",
    alignItems: "baseline",
    gap: 12,
    flex: "1 1 auto",
    minWidth: 160,
  },
  matchTime: {
    fontFamily: "'IBM Plex Mono', monospace",
    fontSize: 13,
    fontWeight: 600,
    color: "#F2C14E",
    minWidth: 48,
    letterSpacing: "0.02em",
  },
  matchTimeFB: {
    fontFamily: "'IBM Plex Mono', monospace",
    fontSize: 12,
    fontWeight: 600,
    color: "#8B919C",
    minWidth: 48,
    fontStyle: "italic",
  },
  matchTeams: { fontSize: 14, fontWeight: 500, flex: 1, display: "inline-flex", alignItems: "center", gap: 6, flexWrap: "wrap" },
  medalMark: {
    fontSize: 16,
    lineHeight: 1,
    flexShrink: 0,
    filter: "drop-shadow(0 1px 1px rgba(0,0,0,0.35))",
  },
  medalToggle: {
    display: "inline-flex",
    alignItems: "center",
    gap: 8,
    fontSize: 12,
    color: "#E8D48B",
    fontFamily: "'Inter', sans-serif",
    fontWeight: 600,
    marginTop: 6,
    userSelect: "none",
  },
  medalSelect: {
    background: "#14161A",
    color: "#EDEFF3",
    border: "1px solid #2C303A",
    borderRadius: 8,
    fontSize: 12,
    fontFamily: "'Inter', sans-serif",
    padding: "6px 8px",
    minHeight: 36,
  },
  matchLiveOn: {
    fontFamily: "'IBM Plex Mono', monospace",
    fontSize: 11,
    color: "#F2C14E",
    display: "flex",
    alignItems: "center",
    flexWrap: "wrap",
    gap: 4,
    flexShrink: 0,
  },
  matchLiveOnChannelChip: {
    display: "inline-flex",
    alignItems: "center",
    background: "#F2EFE9",
    borderRadius: 3,
    padding: "1px 4px",
  },
  matchLiveOnChannelChipText: {
    display: "inline-flex",
    alignItems: "center",
    color: "#F2C14E",
  },
  matchLiveOnLabel: {
    color: "#767C89",
    letterSpacing: "0.08em",
    fontSize: 9,
  },
  matchLiveOnLogo: {
    height: 16,
    width: "auto",
    maxWidth: 70,
    objectFit: "contain",
    display: "block",
  },
  vs: { color: "#767C89", fontSize: 12, margin: "0 4px" },
  mutedSmall: { fontSize: 12, color: "#767C89" },
  overlay: {
    position: "fixed",
    inset: 0,
    background: "rgba(6, 8, 12, 0.78)",
    display: "flex",
    alignItems: "flex-end",
    justifyContent: "center",
    padding: 0,
    zIndex: 50,
  },
  modal: {
    background: "linear-gradient(180deg, #1E232C 0%, #181B22 100%)",
    border: "1px solid #2A2F3A",
    borderRadius: "18px 18px 0 0",
    padding: "18px 16px 12px",
    width: "100%",
    maxHeight: "90dvh",
    overflow: "hidden",
    WebkitOverflowScrolling: "touch",
    display: "flex",
    flexDirection: "column",
    boxSizing: "border-box",
    boxShadow: "0 16px 48px rgba(0,0,0,0.5)",
  },
  modalTitle: {
    fontFamily: "'Teko', sans-serif",
    fontSize: 22,
    fontWeight: 600,
    marginBottom: 10,
    flexShrink: 0,
    letterSpacing: "0.02em",
  },
  modalBody: {
    flex: 1,
    overflowY: "auto",
    WebkitOverflowScrolling: "touch",
    paddingBottom: 4,
    paddingRight: 2,
  },
  modalSection: {
    marginTop: 12,
    marginBottom: 4,
  },
  input: {
    width: "100%",
    background: "#14161A",
    border: "1px solid #2C303A",
    borderRadius: 10,
    padding: "12px 14px",
    color: "#EDEFF3",
    fontSize: 15,
    fontFamily: "'Inter', sans-serif",
    marginBottom: 10,
    boxSizing: "border-box",
    outline: "none",
    transition: "border-color 0.15s ease",
  },
  matchEditorLabel: {
    fontFamily: "'IBM Plex Mono', monospace",
    fontSize: 10,
    color: "#767C89",
    letterSpacing: "0.08em",
    margin: "12px 0 8px",
    textTransform: "uppercase",
  },
  formatToggleRow: { display: "flex", gap: 8, marginBottom: 14 },
  formatBtn: {
    flex: 1,
    background: "#14161A",
    border: "1px solid #2C303A",
    borderRadius: 10,
    color: "#767C89",
    padding: "12px 10px",
    fontSize: 13,
    cursor: "pointer",
    fontFamily: "'Inter', sans-serif",
    minHeight: 44,
  },
  formatBtnActive: {
    flex: 1,
    background: "rgba(61,220,151,0.12)",
    border: "1px solid #3DDC97",
    borderRadius: 10,
    color: "#3DDC97",
    padding: "12px 10px",
    fontSize: 13,
    fontWeight: 600,
    cursor: "pointer",
    fontFamily: "'Inter', sans-serif",
    minHeight: 44,
  },
  matchEditGroup: {
    marginBottom: 12,
    padding: "12px",
    background: "#14161A",
    border: "1px solid #2C303A",
    borderRadius: 10,
  },
  matchEditRow: {
    display: "flex",
    flexWrap: "wrap",
    gap: 8,
    marginBottom: 8,
    alignItems: "center",
  },
  // Satu baris: input + tombol hapus (tidak wrap)
  channelRow: {
    display: "flex",
    flexWrap: "nowrap",
    gap: 8,
    marginBottom: 8,
    alignItems: "center",
    width: "100%",
  },
  channelInput: {
    flex: 1,
    minWidth: 0,
    background: "#1D2027",
    border: "1px solid #2C303A",
    borderRadius: 8,
    color: "#EDEFF3",
    padding: "12px 12px",
    fontSize: 16,
    fontFamily: "'Inter', sans-serif",
    boxSizing: "border-box",
    outline: "none",
    minHeight: 44,
  },
  fbBadgeInput: {
    width: "100%",
    maxWidth: 120,
    flexShrink: 0,
    background: "#1D2027",
    border: "1px solid #2C303A",
    borderRadius: 8,
    color: "#767C89",
    padding: "12px 10px",
    fontFamily: "'IBM Plex Mono', monospace",
    fontSize: 14,
    textAlign: "center",
    minHeight: 44,
    boxSizing: "border-box",
  },
  fbToggleLabel: {
    display: "flex",
    alignItems: "center",
    gap: 8,
    fontSize: 13,
    color: "#A0A6B0",
    marginBottom: 10,
    fontFamily: "'Inter', sans-serif",
    cursor: "pointer",
    minHeight: 44,
  },
  liveOnInput: {
    width: "100%",
    background: "#1D2027",
    border: "1px solid #2C303A",
    borderRadius: 8,
    color: "#EDEFF3",
    padding: "12px 12px",
    fontSize: 16,
    fontFamily: "'Inter', sans-serif",
    boxSizing: "border-box",
    outline: "none",
    minHeight: 44,
  },
  courtInput: {
    width: "100%",
    background: "#1D2027",
    border: "1px solid #2C303A",
    borderRadius: 8,
    color: "#EDEFF3",
    padding: "12px 12px",
    fontSize: 16,
    fontFamily: "'Inter', sans-serif",
    boxSizing: "border-box",
    outline: "none",
    marginBottom: 8,
    minHeight: 44,
  },
  timeInputSmall: {
    background: "#1D2027",
    border: "1px solid #2C303A",
    borderRadius: 8,
    color: "#EDEFF3",
    padding: "12px 10px",
    fontFamily: "'IBM Plex Mono', monospace",
    fontSize: 16,
    width: "100%",
    maxWidth: 140,
    flex: "1 1 120px",
    minHeight: 44,
    boxSizing: "border-box",
  },
  teamInput: {
    flex: "1 1 120px",
    background: "#1D2027",
    border: "1px solid #2C303A",
    borderRadius: 8,
    color: "#EDEFF3",
    padding: "12px 12px",
    fontSize: 16,
    fontFamily: "'Inter', sans-serif",
    minWidth: 0,
    minHeight: 44,
    boxSizing: "border-box",
  },
  rowRemoveBtn: {
    background: "rgba(118,124,137,0.15)",
    border: "1px solid #2C303A",
    color: "#A0A6B0",
    fontSize: 18,
    cursor: "pointer",
    padding: 0,
    flexShrink: 0,
    width: 44,
    height: 44,
    borderRadius: 8,
    display: "inline-flex",
    alignItems: "center",
    justifyContent: "center",
  },
  addMatchBtn: {
    background: "none",
    border: "1px dashed #2C303A",
    color: "#3DDC97",
    borderRadius: 8,
    padding: "12px 12px",
    fontSize: 14,
    cursor: "pointer",
    width: "100%",
    marginBottom: 14,
    fontFamily: "'Inter', sans-serif",
    minHeight: 44,
  },
  modalActions: {
    display: "flex",
    gap: 10,
    paddingTop: 12,
    paddingBottom: "max(12px, env(safe-area-inset-bottom))",
    borderTop: "1px solid #2C303A",
    marginTop: 8,
    flexShrink: 0,
    background: "#1D2027",
  },
  authErrorText: { color: "#FF6B6B", fontSize: 12, marginTop: -6, marginBottom: 10 },
  secondaryBtn: {
    flex: 1,
    background: "transparent",
    color: "#EDEFF3",
    border: "1px solid #2C303A",
    borderRadius: 10,
    padding: "14px 16px",
    fontSize: 15,
    cursor: "pointer",
    fontFamily: "'Inter', sans-serif",
    minHeight: 48,
  },
  primaryBtn: {
    flex: 1,
    background: "linear-gradient(145deg, #4AE6A8 0%, #2BC98A 100%)",
    color: "#0E1014",
    border: "none",
    borderRadius: 12,
    padding: "14px 16px",
    fontSize: 15,
    fontWeight: 600,
    cursor: "pointer",
    fontFamily: "'Inter', sans-serif",
    minHeight: 48,
  },
  fabWrap: {
    position: "fixed",
    bottom: 24,
    right: 20,
    display: "flex",
    flexDirection: "column",
    alignItems: "flex-end",
    gap: 12,
    zIndex: 30,
  },
  fabMain: {
    width: 56,
    height: 56,
    borderRadius: "50%",
    background: "linear-gradient(145deg, #4AE6A8 0%, #2BC98A 100%)",
    color: "#0E1014",
    border: "none",
    fontSize: 28,
    fontWeight: 400,
    lineHeight: 1,
    cursor: "pointer",
    boxShadow: "0 6px 20px rgba(61,220,151,0.4)",
    transition: "transform 0.15s ease, box-shadow 0.15s ease",
  },
  fabMainOpen: {
    width: 56,
    height: 56,
    borderRadius: "50%",
    background: "linear-gradient(145deg, #4AE6A8 0%, #2BC98A 100%)",
    color: "#0E1014",
    border: "none",
    fontSize: 28,
    fontWeight: 400,
    lineHeight: 1,
    cursor: "pointer",
    boxShadow: "0 6px 20px rgba(61,220,151,0.4)",
    transform: "rotate(45deg)",
  },
  fabOption: {
    display: "flex",
    alignItems: "center",
    gap: 10,
    background: "none",
    border: "none",
    cursor: "pointer",
    padding: 0,
  },
  fabOptionLabel: {
    background: "#1C2028",
    border: "1px solid #2A2F3A",
    color: "#EDEFF3",
    borderRadius: 10,
    padding: "8px 12px",
    fontSize: 12,
    fontWeight: 500,
    fontFamily: "'Inter', sans-serif",
    whiteSpace: "nowrap",
    boxShadow: "0 4px 14px rgba(0,0,0,0.35)",
  },
  fabOptionCircle: {
    width: 42,
    height: 42,
    borderRadius: "50%",
    background: "#1C2028",
    border: "1px solid #2A2F3A",
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    fontSize: 18,
    boxShadow: "0 2px 8px rgba(0,0,0,0.3)",
    flexShrink: 0,
  },
  toast: {
    position: "fixed",
    bottom: 28,
    left: "50%",
    transform: "translateX(-50%)",
    background: "#3DDC97",
    color: "#0E1014",
    padding: "12px 20px",
    borderRadius: 999,
    fontSize: 13,
    fontWeight: 600,
    fontFamily: "'Inter', sans-serif",
    boxShadow: "0 8px 28px rgba(61,220,151,0.35)",
    zIndex: 80,
  },
};

export { fontImports, styles };
